# Generated by Django 4.2.30 on 2026-07-23 01:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="会社名")),
                (
                    "parent_company",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="親会社"
                    ),
                ),
                (
                    "business_description",
                    models.TextField(blank=True, verbose_name="会社がしてること"),
                ),
                ("website_url", models.URLField(blank=True, verbose_name="会社URL")),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, verbose_name="所在地"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="company_logos/",
                        verbose_name="企業ロゴ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名前")),
                (
                    "furigana",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ふりがな/ローマ字"
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=100, verbose_name="部署名"),
                ),
                ("role", models.CharField(max_length=100, verbose_name="役名")),
                ("career_history", models.TextField(blank=True, verbose_name="経歴")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="メールアドレス"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="電話番号"
                    ),
                ),
                (
                    "sns_links",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="SNSリンク集"
                    ),
                ),
                (
                    "custom_card_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="custom_cards/",
                        verbose_name="カスタム名刺画像",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="api.company",
                        verbose_name="所属会社",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NFCCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="タグID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="有効ステータス"),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card",
                        to="api.employeeprofile",
                        verbose_name="紐づく社員",
                    ),
                ),
            ],
        ),
    ]
